name: GoodWatch
options:
  bundleIdPrefix: com.parikshit.goodwatch
  deploymentTarget:
    iOS: "17.0"

packages:
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"
  GoogleSignIn-iOS:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "7.0.0"

targets:
  GoodWatch:
    type: application
    platform: iOS
    sources:
      - GoodWatch
    dependencies:
      - package: firebase-ios-sdk
        product: FirebaseAnalytics
      - package: GoogleSignIn-iOS
        product: GoogleSignIn
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.parikshit.goodwatch.movies
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: H827NY6Y9W
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: Apple Development
    info:
      path: GoodWatch/Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    scheme:
      testTargets: []
      gatherCoverageData: false
